=== Bernardo-MG/Tabletop-Pendragon-Framework/src/test/resources/validation/additional-belongings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="additional_belongings">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" />
				<xs:element name="belongings_table" type="belongingsTable" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="belongingsTable">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="belongings_row" type="belongingsRow" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="belongingsRow">
		<xs:all>
			<xs:element name="lower_limit" type="xs:integer" />
			<xs:element name="belongings" type="belongingsData" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="belongingsData">
		<xs:all>
			<xs:element name="money" type="moneyData" minOccurs="0" />
			<xs:element name="reroll" type="storedReroll" minOccurs="0" />
			<xs:element name="horses" type="storedHorse" minOccurs="0" />
			<xs:element name="items" type="storedItem" minOccurs="0" />
			<xs:element name="shields" type="storedShields" minOccurs="0" />
			<xs:element name="weapons" type="storedWeapons" minOccurs="0" />
			<xs:element name="pets" type="storedPet" minOccurs="0" />
			<xs:element name="has_to_choose" type="xs:boolean" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="storedPet">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="pet" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="storedItem">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="item" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="storedShields">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="shield" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="storedWeapons">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="weapon" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="storedHorse">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="horse" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="storedReroll">
		<xs:sequence>
			<xs:element name="reroll_table" type="xs:string" />
			<xs:element name="rerolls" type="rerollsList" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="rerollsList">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="reroll" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="\d+d\d+([+-]\d+)?" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="moneyData">
		<xs:all>
			<xs:element name="name" type="xs:string" />
			<xs:element name="libra" type="xs:integer" />
			<xs:element name="denarii" type="xs:integer" />
		</xs:all>
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/Tabletop-Pendragon-Framework/src/test/resources/model/files/additional-belongings.xml
<?xml version="1.0" encoding="UTF-8"?>
<additional_belongings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../validation/additional-belongings.xsd">
	<name>test_additional_belongings</name>
	<belongings_table>
		<belongings_row>
			<lower_limit>1</lower_limit>
			<belongings>
				<money>
					<name>test_money</name>
					<libra>11</libra>
					<denarii>22</denarii>
				</money>
				<has_to_choose>false</has_to_choose>
			</belongings>
		</belongings_row>
		<belongings_row>
			<lower_limit>5</lower_limit>
			<belongings>
				<reroll>
					<reroll_table>table_1</reroll_table>
					<rerolls>
						<reroll>1d6</reroll>
						<reroll>1d20+1</reroll>
					</rerolls>
				</reroll>
				<has_to_choose>false</has_to_choose>
			</belongings>
		</belongings_row>
		<belongings_row>
			<lower_limit>7</lower_limit>
			<belongings>
				<horses>
					<horse>horse_1</horse>
					<horse>horse_2</horse>
				</horses>
				<has_to_choose>true</has_to_choose>
			</belongings>
		</belongings_row>
		<belongings_row>
			<lower_limit>10</lower_limit>
			<belongings>
				<items>
					<item>item_1</item>
					<item>item_2</item>
				</items>
				<has_to_choose>false</has_to_choose>
			</belongings>
		</belongings_row>
		<belongings_row>
			<lower_limit>12</lower_limit>
			<belongings>
				<shields>
					<shield>shield_1</shield>
					<shield>shield_2</shield>
				</shields>
				<has_to_choose>false</has_to_choose>
			</belongings>
		</belongings_row>
		<belongings_row>
			<lower_limit>13</lower_limit>
			<belongings>
				<weapons>
					<weapon>weapon_1</weapon>
					<weapon>weapon_2</weapon>
				</weapons>
				<has_to_choose>false</has_to_choose>
			</belongings>
		</belongings_row>
		<belongings_row>
			<lower_limit>15</lower_limit>
			<belongings>
				<pets>
					<pet>pet_1</pet>
					<pet>pet_2</pet>
				</pets>
				<has_to_choose>false</has_to_choose>
			</belongings>
		</belongings_row>
	</belongings_table>
</additional_belongings>
