=== Bernardo-MG/Tabletop-Pendragon-Framework/src/test/resources/validation/culture.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="culture">
		<xs:complexType>
			<xs:all>
				<xs:element name="name" type="xs:string" />
				<xs:element name="family_characteristic" type="genderPair" />
				<xs:element name="initial_luck" type="genderPair" />
				<xs:element name="template" type="templateBaseGenders" />
			</xs:all>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="genderPair">
		<xs:all>
			<xs:element name="female" type="xs:token" />
			<xs:element name="male" type="xs:token" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="templateBaseGenders">
		<xs:all>
			<xs:element name="female" type="templateBase" />
			<xs:element name="male" type="templateBase" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="templateBase">
		<xs:all>
			<xs:element name="attributes_bonus" type="attributesBonus" />
			<xs:element name="attributes_random" type="attributesRandom" />
			<xs:element name="traits_bonus" type="traitsBonus" />
			<xs:element name="skills_bonus" type="skillsBonus" />
			<xs:element name="specialty_skills" type="specialtySkills" />
			<xs:element name="passions_bonus" type="passionsBonus" />
			<xs:element name="passions_random" type="passionsRandom" />
			<xs:element name="directed_traits_bonus" type="directedTraitsBonus" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="attributesBonus">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="attribute" type="characteristic" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="attributesRandom">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="attribute" type="characteristicRandom" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="traitsBonus">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="trait" type="characteristic" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="passionsBonus">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="passion" type="skill" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="passionsRandom">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="passion" type="skillRandom" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="skillsBonus">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="skill" type="skill" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="specialtySkills">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="specialty_skill" type="characteristic" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="directedTraitsBonus">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="directed_trait" type="skill" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="characteristic">
		<xs:all>
			<xs:element name="name" type="xs:token" />
			<xs:element name="value" type="xs:integer" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="characteristicRandom">
		<xs:all>
			<xs:element name="name" type="xs:token" />
			<xs:element name="value" type="xs:token" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="skill">
		<xs:all>
			<xs:element name="name" type="xs:token" />
			<xs:element name="descriptor" type="xs:token" minOccurs="0" />
			<xs:element name="value" type="xs:integer" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="skillRandom">
		<xs:all>
			<xs:element name="name" type="xs:token" />
			<xs:element name="descriptor" type="xs:token" minOccurs="0" />
			<xs:element name="value" type="xs:token" />
		</xs:all>
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/Tabletop-Pendragon-Framework/src/test/resources/model/files/culture.xml
<?xml version="1.0" encoding="UTF-8"?>
<culture xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="..\..\validation\culture.xsd">
	<name>culture_1</name>
	<family_characteristic>
		<female>char_female</female>
		<male>char_male</male>
	</family_characteristic>
	<initial_luck>
		<female>luck_female</female>
		<male>luck_male</male>
	</initial_luck>
	<template>
		<male>
			<attributes_bonus>
				<attribute>
					<name>attribute_1</name>
					<value>1</value>
				</attribute>
				<attribute>
					<name>attribute_2</name>
					<value>2</value>
				</attribute>
			</attributes_bonus>
			<attributes_random>
				<attribute>
					<name>attribute_1</name>
					<value>1d6</value>
				</attribute>
				<attribute>
					<name>attribute_2</name>
					<value>2d6</value>
				</attribute>
			</attributes_random>
			<traits_bonus>
				<trait>
					<name>trait_1</name>
					<value>6</value>
				</trait>
				<trait>
					<name>trait_2</name>
					<value>12</value>
				</trait>
			</traits_bonus>
			<skills_bonus>
				<skill>
					<name>skill_1</name>
					<value>10</value>
				</skill>
				<skill>
					<name>skill_2</name>
					<descriptor>descriptor_2</descriptor>
					<value>11</value>
				</skill>
			</skills_bonus>
			<specialty_skills>
				<specialty_skill>
					<name>specialty_1</name>
					<value>15</value>
				</specialty_skill>
				<specialty_skill>
					<name>specialty_2</name>
					<value>16</value>
				</specialty_skill>
			</specialty_skills>
			<passions_bonus>
				<passion>
					<name>passion_1</name>
					<value>17</value>
				</passion>
				<passion>
					<name>passion_2</name>
					<descriptor>descriptor_2</descriptor>
					<value>24</value>
				</passion>
			</passions_bonus>
			<passions_random>
				<passion>
					<name>passion_1</name>
					<value>3d6</value>
				</passion>
				<passion>
					<name>passion_2</name>
					<descriptor>descriptor_2</descriptor>
					<value>0</value>
				</passion>
				<passion>
					<name>passion_4</name>
					<value>5</value>
				</passion>
			</passions_random>
			<directed_traits_bonus>
				<directed_trait>
					<name>directed_1</name>
					<value>30</value>
				</directed_trait>
				<directed_trait>
					<name>directed_2</name>
					<descriptor>descriptor_2</descriptor>
					<value>1</value>
				</directed_trait>
			</directed_traits_bonus>
		</male>
		<female>
			<attributes_bonus>
				<attribute>
					<name>attribute_3</name>
					<value>3</value>
				</attribute>
			</attributes_bonus>
			<attributes_random>
				<attribute>
					<name>attribute_3</name>
					<value>10d2</value>
				</attribute>
			</attributes_random>
			<traits_bonus>
				<trait>
					<name>trait_3</name>
					<value>22</value>
				</trait>
			</traits_bonus>
			<skills_bonus>
				<skill>
					<name>skill_3</name>
					<value>12</value>
				</skill>
			</skills_bonus>
			<specialty_skills>
				<specialty_skill>
					<name>specialty_3</name>
					<value>17</value>
				</specialty_skill>
			</specialty_skills>
			<passions_bonus>
				<passion>
					<name>passion_3</name>
					<value>18</value>
				</passion>
			</passions_bonus>
			<passions_random>
				<passion>
					<name>passion_3</name>
					<value>6d6</value>
				</passion>
			</passions_random>
			<directed_traits_bonus>
				<directed_trait>
					<name>directed_3</name>
					<value>31</value>
				</directed_trait>
			</directed_traits_bonus>
		</female>
	</template>
</culture>
