=== Bernardo-MG/Tabletop-Pendragon-Framework/src/test/resources/validation/family-characteristic.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="family_characteristic_table">
		<xs:complexType>
			<xs:all>
				<xs:element name="name" type="xs:string" />
				<xs:element name="intervals" type="intervalList">
					<xs:unique name="uniqueCharacteristic">
						<xs:selector xpath="interval/family_characteristic" />
						<xs:field xpath="name" />
					</xs:unique>
					<xs:unique name="uniqueLimit">
						<xs:selector xpath="interval" />
						<xs:field xpath="lower_limit" />
					</xs:unique>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="intervalList">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="interval" type="interval" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="interval">
		<xs:all>
			<xs:element name="lower_limit" type="xs:integer" />
			<xs:element name="family_characteristic" type="familyCharacteristic" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="familyCharacteristic">
		<xs:all>
			<xs:element name="name" type="xs:token" />
			<xs:element name="bonus" type="bonusList" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="bonusList">
		<xs:all>
			<xs:element name="attributes" type="attributesList"
				minOccurs="0" />
			<xs:element name="skills" type="skillsList" minOccurs="0" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="attributesList">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="attribute" type="attributeNode" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="skillsList">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="skill" type="skillNode" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="attributeNode">
		<xs:all>
			<xs:element name="name" type="xs:token" />
			<xs:element name="value" type="xs:integer" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="skillNode">
		<xs:all>
			<xs:element name="name" type="xs:token" />
			<xs:element name="descriptor" type="xs:token" minOccurs="0" />
			<xs:element name="value" type="xs:integer" />
		</xs:all>
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/Tabletop-Pendragon-Framework/src/test/resources/model/files/family-characteristic.xml
<?xml version="1.0" encoding="UTF-8"?>
<family_characteristic_table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../validation/family-characteristic.xsd">
	<name>test_family_characteristic</name>
	<intervals>
		<interval>
			<lower_limit>1</lower_limit>
			<family_characteristic>
				<name>characteristic_1</name>
				<bonus>
					<skills>
						<skill>
							<name>skill_1</name>
							<value>3</value>
						</skill>
						<skill>
							<name>skill_2</name>
							<descriptor>descriptor_skill_2</descriptor>
							<value>4</value>
						</skill>
					</skills>
				</bonus>
			</family_characteristic>
		</interval>
		<interval>
			<lower_limit>5</lower_limit>
			<family_characteristic>
				<name>characteristic_2</name>
				<bonus>
					<attributes>
						<attribute>
							<name>appearance</name>
							<value>7</value>
						</attribute>
					</attributes>
					<skills>
						<skill>
							<name>skill_1</name>
							<value>3</value>
						</skill>
					</skills>
				</bonus>
			</family_characteristic>
		</interval>
	</intervals>
</family_characteristic_table>
