=== Bernardo-MG/Tabletop-Pendragon-Framework/src/test/resources/validation/pendragon-model-skill.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- Validation file for Skills model XML files -->

	<!-- ************************************************************ -->
	<!-- *************************** ROOT *************************** -->
	<!-- ************************************************************ -->

	<xs:element name="skills">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="skill" type="skill" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueData">
			<xs:selector xpath="skill" />
			<xs:field xpath="name" />
		</xs:unique>
	</xs:element>

	<xs:complexType name="skill">
		<xs:sequence>
			<xs:element name="name" type="xs:token" />
			<xs:element name="descriptor" type="xs:token" minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="combat" type="xs:boolean" default="false" />
		<xs:attribute name="courtly" type="xs:boolean" default="false" />
		<xs:attribute name="knightly" type="xs:boolean" default="false" />
		<xs:attribute name="knowledge" type="xs:boolean" default="false" />
		<xs:attribute name="repeatable" type="xs:boolean"
			default="false" />
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/Tabletop-Pendragon-Framework/src/main/resources/model/pendragon-model-skill.xml
<?xml version="1.0" encoding="UTF-8"?>
<skills xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="validation/pendragon-model-skill.xsd">
	<skill knightly="true">
		<name>awareness</name>
	</skill>
	<skill combat="true" knightly="true">
		<name>axe</name>
	</skill>
	<skill combat="true" knightly="true">
		<name>battle</name>
	</skill>
	<skill knightly="true">
		<name>boating</name>
	</skill>
	<skill combat="true" knightly="true">
		<name>bow</name>
	</skill>
	<skill combat="true" knightly="true">
		<name>charioteer</name>
	</skill>
	<skill>
		<name>chirurgery</name>
	</skill>
	<skill courtly="true" knightly="true">
		<name>compose</name>
	</skill>
	<skill combat="true" knightly="true">
		<name>compound_bow</name>
	</skill>
	<skill courtly="true" knightly="true" knowledge="true">
		<name>courtesy</name>
	</skill>
	<skill combat="true">
		<name>crossbow</name>
	</skill>
	<skill combat="true" knightly="true">
		<name>dagger</name>
	</skill>
	<skill courtly="true" knightly="true">
		<name>dancing</name>
	</skill>
	<skill knightly="true" knowledge="true">
		<name>faerie_lore</name>
	</skill>
	<skill courtly="true" knightly="true" knowledge="true">
		<name>falconry</name>
	</skill>
	<skill courtly="true">
		<name>fashion</name>
	</skill>
	<skill knightly="true">
		<name>first_aid</name>
	</skill>
	<skill combat="true" knightly="true">
		<name>flail</name>
	</skill>
	<skill courtly="true" knightly="true">
		<name>flirting</name>
	</skill>
	<skill knightly="true">
		<name>folklore</name>
	</skill>
	<skill courtly="true" knightly="true">
		<name>gaming</name>
	</skill>
	<skill combat="true" knightly="true">
		<name>grapple</name>
	</skill>
	<skill combat="true" knightly="true">
		<name>great_axe</name>
	</skill>
	<skill combat="true" knightly="true">
		<name>great_lance</name>
	</skill>
	<skill combat="true" knightly="true">
		<name>great_mace</name>
	</skill>
	<skill combat="true" knightly="true">
		<name>great_spear</name>
	</skill>
	<skill combat="true" knightly="true">
		<name>great_sword</name>
	</skill>
	<skill combat="true" knightly="true">
		<name>halberd</name>
	</skill>
	<skill combat="true" knightly="true">
		<name>hammer</name>
	</skill>
	<skill courtly="true" knightly="true" knowledge="true">
		<name>heraldry</name>
	</skill>
	<skill combat="true" knightly="true">
		<name>horsemanship</name>
	</skill>
	<skill knightly="true">
		<name>hunting</name>
	</skill>
	<skill>
		<name>industry</name>
	</skill>
	<skill courtly="true" knightly="true">
		<name>intrigue</name>
	</skill>
	<skill combat="true" knightly="true">
		<name>javelin</name>
	</skill>
	<skill combat="true" knightly="true">
		<name>lance</name>
	</skill>
	<skill combat="true" knightly="true">
		<name>mace</name>
	</skill>
	<skill combat="true" knightly="true">
		<name>morning_star</name>
	</skill>
	<skill courtly="true" knightly="true">
		<name>orate</name>
	</skill>
	<skill courtly="true" knightly="true" repeatable="true">
		<name>play</name>
		<descriptor>instrument</descriptor>
	</skill>
	<skill courtly="true" knightly="true" knowledge="true" repeatable="true">
		<name>read</name>
		<descriptor>written_language</descriptor>
	</skill>
	<skill courtly="true" knightly="true" knowledge="true">
		<name>recognize</name>
	</skill>
	<skill knightly="true" knowledge="true" repeatable="true">
		<name>religion</name>
		<descriptor>religion</descriptor>
	</skill>
	<skill courtly="true" knightly="true" knowledge="true">
		<name>romance</name>
	</skill>
	<skill combat="true" knightly="true">
		<name>siege</name>
	</skill>
	<skill courtly="true" knightly="true" knowledge="true">
		<name>singing</name>
	</skill>
	<skill combat="true" knightly="true">
		<name>spear</name>
	</skill>
	<skill knightly="true" knowledge="true">
		<name>stewardship</name>
	</skill>
	<skill combat="true" knightly="true">
		<name>sword</name>
	</skill>
	<skill knightly="true">
		<name>swimming</name>
	</skill>
	<skill courtly="true" knightly="true" knowledge="true">
		<name>tourney</name>
	</skill>
	<skill combat="true" knightly="true">
		<name>warflail</name>
	</skill>
</skills>

=== Bernardo-MG/Tabletop-Pendragon-Framework/src/test/resources/model/files/skills.xml
<?xml version="1.0" encoding="UTF-8"?>
<skills xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../validation/pendragon-model-skill.xsd">
	<skill >
		<name>skill_1</name>
	</skill>
	<skill combat="true" knightly="true">
		<name>skill_2</name>
	</skill>
	<skill courtly="true" knightly="true" knowledge="true" repeatable="true">
		<name>skill_3</name>
		<descriptor>descriptor_3</descriptor>
	</skill>
</skills>
