=== Bernardo-MG/Tabletop-Pendragon-Framework/src/test/resources/validation/pet.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="pet">
		<xs:complexType>
			<xs:all>
				<xs:element name="name" type="xs:string" />
				<xs:element name="year_results_table" type="yearResults" />
			</xs:all>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="yearResults">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="year_result" type="yearResult" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="yearResult">
		<xs:all>
			<xs:element name="description" type="xs:string" />
			<xs:element name="interval" type="intervalData" />
			<xs:element name="puppy_name" type="xs:string" minOccurs="0" />
			<xs:element name="dies" type="xs:boolean" minOccurs="0" />
			<xs:element name="money" type="moneyData" minOccurs="0" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="intervalData">
		<xs:all>
			<xs:element name="lower_limit" type="xs:integer" />
			<xs:element name="upper_limit" type="xs:integer" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="moneyData">
		<xs:all>
			<xs:element name="libra" type="xs:integer" />
			<xs:element name="denarii" type="xs:integer" />
		</xs:all>
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/Tabletop-Pendragon-Framework/src/test/resources/model/files/pet.xml
<?xml version="1.0" encoding="UTF-8"?>
<pet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../validation/pet.xsd">
	<name>test_pet</name>
	<year_results_table>
		<year_result>
			<description>description_1</description>
			<lower_limit>1</lower_limit>
		</year_result>
		<year_result>
			<description>description_2</description>
			<lower_limit>6</lower_limit>
			<puppy_name>puppy_1</puppy_name>
		</year_result>
		<year_result>
			<description>description_3</description>
			<lower_limit>11</lower_limit>
			<dies>true</dies>
		</year_result>
		<year_result>
			<description>description_4</description>
			<lower_limit>13</lower_limit>
			<money>
				<libra>11</libra>
				<denarii>22</denarii>
			</money>
		</year_result>
	</year_results_table>
</pet>
