=== Bernardo-MG/Tabletop-Pendragon-Framework/src/test/resources/validation/religion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- Validation file for ReligionTemplate XML files -->

	<!-- ************************************************************ -->
	<!-- *************************** ROOT *************************** -->
	<!-- ************************************************************ -->

	<xs:element name="religion">
		<xs:complexType>
			<xs:all>
				<xs:element name="name" type="xs:string" />
				<xs:element name="traits" type="traitsList">
					<xs:unique name="uniqueTrait">
						<xs:selector xpath="trait" />
						<xs:field xpath="." />
					</xs:unique>
				</xs:element>
				<xs:element name="bonus" type="bonusList" minOccurs="0" />
			</xs:all>
		</xs:complexType>
	</xs:element>

	<!-- ************************************************************ -->
	<!-- *********************** VALUES LISTS *********************** -->
	<!-- ************************************************************ -->

	<xs:complexType name="bonusList">
		<xs:all minOccurs="0">
			<xs:element name="derived_attributes" type="derivedAttributesList">
				<xs:unique name="uniqueDerived">
					<xs:selector xpath="derived_attribute" />
					<xs:field xpath="name" />
				</xs:unique>
			</xs:element>
			<xs:element name="armor_bonus" type="xs:integer" />
			<xs:element name="damage_bonus" type="xs:integer" />
			<xs:element name="damage_dice_bonus" type="xs:integer" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="traitsList">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="trait" type="traitType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="derivedAttributesList">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="derived_attribute" type="bonusNode" />
		</xs:sequence>
	</xs:complexType>

	<!-- ************************************************************ -->
	<!-- ************************** VALUES ************************** -->
	<!-- ************************************************************ -->

	<xs:complexType name="bonusNode">
		<xs:all>
			<xs:element name="name" type="xs:token" />
			<xs:element name="value" type="xs:integer" />
		</xs:all>
	</xs:complexType>

	<!-- ************************************************************ -->
	<!-- ************************** ENUMS *************************** -->
	<!-- ************************************************************ -->

	<!-- Traits -->
	<xs:simpleType name="traitType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="arbitrary" />
			<xs:enumeration value="chaste" />
			<xs:enumeration value="cowardly" />
			<xs:enumeration value="cruel" />
			<xs:enumeration value="deceitful" />
			<xs:enumeration value="energetic" />
			<xs:enumeration value="forgiving" />
			<xs:enumeration value="generous" />
			<xs:enumeration value="honest" />
			<xs:enumeration value="indulgent" />
			<xs:enumeration value="just" />
			<xs:enumeration value="lazy" />
			<xs:enumeration value="lustful" />
			<xs:enumeration value="merciful" />
			<xs:enumeration value="modest" />
			<xs:enumeration value="pious" />
			<xs:enumeration value="proud" />
			<xs:enumeration value="prudent" />
			<xs:enumeration value="reckless" />
			<xs:enumeration value="selfish" />
			<xs:enumeration value="suspicious" />
			<xs:enumeration value="temperate" />
			<xs:enumeration value="trusting" />
			<xs:enumeration value="valorous" />
			<xs:enumeration value="vengeful" />
			<xs:enumeration value="wordly" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== Bernardo-MG/Tabletop-Pendragon-Framework/src/test/resources/model/files/religion.xml
<?xml version="1.0" encoding="UTF-8"?>
<religion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="..\..\validation\religion.xsd">
	<name>test_religion</name>
	<traits>
		<trait>chaste</trait>
		<trait>honest</trait>
		<trait>just</trait>
		<trait>merciful</trait>
		<trait>temperate</trait>
	</traits>
	<bonus>
		<derived_attributes>
			<derived_attribute>
				<name>damage_bonus</name>
				<value>3</value>
			</derived_attribute>
			<derived_attribute>
				<name>hitpoints</name>
				<value>2</value>
			</derived_attribute>
		</derived_attributes>
		<armor_bonus>5</armor_bonus>
		<damage_bonus>6</damage_bonus>
		<damage_dice_bonus>7</damage_dice_bonus>
	</bonus>
</religion>
