=== Bernardo-MG/Tabletop-Pendragon-Framework/src/main/resources/model/validation/pendragon-model-attribute.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="attributes">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="attribute" type="attribute" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueData">
			<xs:selector xpath="attribute" />
			<xs:field xpath="name" />
		</xs:unique>
	</xs:element>

	<xs:complexType name="attribute">
		<xs:sequence>
			<xs:element name="name" type="xs:token" maxOccurs="1"
				minOccurs="1" />
		</xs:sequence>
		<xs:attribute name="human" type="xs:boolean" default="false" />
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/Tabletop-Pendragon-Framework/src/main/resources/model/pendragon-model-attribute.xml
<?xml version="1.0" encoding="UTF-8"?>
<attributes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="validation/pendragon-model-attribute.xsd">
	<attribute human="true">
		<name>appearance</name>
	</attribute>
	<attribute>
		<name>constitution</name>
	</attribute>
	<attribute>
		<name>dexterity</name>
	</attribute>
	<attribute>
		<name>strength</name>
	</attribute>
	<attribute>
		<name>size</name>
	</attribute>
</attributes>
