=== Bernardo-MG/Tabletop-Pendragon-Framework/src/main/resources/model/validation/pendragon-model-feature.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="features">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="feature" type="feature" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueData">
			<xs:selector xpath="feature" />
			<xs:field xpath="name" />
		</xs:unique>
	</xs:element>

	<xs:complexType name="feature">
		<xs:sequence>
			<xs:element name="name" type="xs:token" maxOccurs="1"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/Tabletop-Pendragon-Framework/src/main/resources/model/pendragon-model-feature.xml
<?xml version="1.0" encoding="UTF-8"?>
<features xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="validation/pendragon-model-feature.xsd">
	<feature>
		<name>body</name>
	</feature>
	<feature>
		<name>expression</name>
	</feature>
	<feature>
		<name>facial</name>
	</feature>
	<feature>
		<name>hair</name>
	</feature>
	<feature>
		<name>limbs</name>
	</feature>
	<feature>
		<name>speech</name>
	</feature>
</features>
