=== Bernardo-MG/Tabletop-Pendragon-Framework/src/main/resources/model/validation/pendragon-model-passion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="passions">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="passion" type="passion" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueData">
			<xs:selector xpath="passion" />
			<xs:field xpath="name" />
			<xs:field xpath="descriptor" />
		</xs:unique>
	</xs:element>

	<xs:complexType name="passion">
		<xs:sequence>
			<xs:element name="name" type="xs:token" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="descriptor" type="xs:token" maxOccurs="1"
				minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="knight" type="xs:boolean" default="false" />
		<xs:attribute name="rare" type="xs:boolean" default="false" />
		<xs:attribute name="repeat" type="xs:boolean" default="false" />
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/Tabletop-Pendragon-Framework/src/main/resources/model/pendragon-model-passion.xml
<?xml version="1.0" encoding="UTF-8"?>
<passions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="validation/pendragon-model-passion.xsd">
	<passion repeatable="true">
		<name>amor</name>
		<descriptor>person</descriptor>
	</passion>
	<passion repeatable="true">
		<name>concern</name>
		<descriptor>group</descriptor>
	</passion>
	<passion repeatable="true">
		<name>fear</name>
		<descriptor>creature_event</descriptor>
	</passion>
	<passion repeatable="true">
		<name>hate</name>
		<descriptor>person_group_nation</descriptor>
	</passion>
	<passion>
		<name>hospitality</name>
	</passion>
	<passion>
		<name>honor</name>
	</passion>
	<passion repeatable="true">
		<name>loyalty</name>
		<descriptor>person_group</descriptor>
	</passion>
	<passion repeatable="true">
		<name>love</name>
		<descriptor>person_group_god</descriptor>
	</passion>
</passions>
