=== Bernardo-MG/Tabletop-Pendragon-Framework/src/main/resources/model/validation/pendragon-model-trait-list.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="traits_list">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="trait" type="xs:token" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueData">
			<xs:selector xpath="trait" />
			<xs:field xpath="." />
		</xs:unique>
	</xs:element>

</xs:schema>

=== Bernardo-MG/Tabletop-Pendragon-Framework/src/main/resources/model/pendragon-model-trait-chivaldry.xml
<?xml version="1.0" encoding="UTF-8"?>
<traits_list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="validation/pendragon-model-trait-list.xsd">
	<trait>energetic</trait>
	<trait>generous</trait>
	<trait>just</trait>
	<trait>merciful</trait>
	<trait>modest</trait>
	<trait>prudent</trait>
	<trait>valorous</trait>
</traits_list>
