=== Bernardo-MG/Tabletop-Pendragon-Framework/src/main/resources/model/validation/pendragon-model-trait.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="traits">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="trait" type="trait" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueData">
			<xs:selector xpath="trait" />
			<xs:field xpath="positive" />
		</xs:unique>
	</xs:element>

	<xs:complexType name="trait">
		<xs:sequence>
			<xs:element name="positive" type="xs:token" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="negative" type="xs:token" maxOccurs="1"
				minOccurs="1" />
		</xs:sequence>
		<xs:attribute name="chivaldry" type="xs:boolean" default="false" />
		<xs:attribute name="gentlewoman" type="xs:boolean"
			default="false" />
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/Tabletop-Pendragon-Framework/src/main/resources/model/pendragon-model-trait.xml
<?xml version="1.0" encoding="UTF-8"?>
<traits xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="validation/pendragon-model-trait.xsd">
	<trait>
		<positive>chaste</positive>
		<negative>lustful</negative>
	</trait>
	<trait>
		<positive>energetic</positive>
		<negative>lazy</negative>
	</trait>
	<trait>
		<positive>forgiving</positive>
		<negative>vengeful</negative>
	</trait>
	<trait>
		<positive>generous</positive>
		<negative>selfish</negative>
	</trait>
	<trait>
		<positive>honest</positive>
		<negative>deceitful</negative>
	</trait>
	<trait>
		<positive>just</positive>
		<negative>arbitrary</negative>
	</trait>
	<trait>
		<positive>merciful</positive>
		<negative>cruel</negative>
	</trait>
	<trait>
		<positive>modest</positive>
		<negative>proud</negative>
	</trait>
	<trait>
		<positive>pious</positive>
		<negative>worldly</negative>
	</trait>
	<trait>
		<positive>prudent</positive>
		<negative>reckless</negative>
	</trait>
	<trait>
		<positive>temperate</positive>
		<negative>indulgent</negative>
	</trait>
	<trait>
		<positive>trusting</positive>
		<negative>suspicious</negative>
	</trait>
	<trait>
		<positive>valorous</positive>
		<negative>cowardly</negative>
	</trait>
</traits>
